#!/bin/bash

 usage_message="    $(basename $0) \"THING I NEED TO DO\"\n"
usage_message+="      Add a package to track (+personal @package) quickly, defaulting priority to '(A) [1.00]'\n"
usage_message+="      Example: $TODO_SH $(basename $0) Backpack from Amazon"

source $(dirname $(readlink -nf "$BASH_SOURCE"))/common

"$TODO_FULL_SH" addq "$@" +personal @package
