#!/bin/bash

 usage_message="    $(basename $0) \"THING I NEED TO DO\"\n"
usage_message+="      Add an item to +work, defaulting priority to '(A) [1.00]'\n"
usage_message+="      Example: $TODO_SH $(basename $0) This is a new item"

source $(dirname $(readlink -nf "$BASH_SOURCE"))/common
[ "$#" -lt 1 ] && usage "Need at least 1 argument"

"$TODO_FULL_SH" add A 1 "$@" "+work"
