#!/bin/bash

 usage_message="    $(basename $0) ITEM# PRIORITY [ADDITIONAL-PRIORITY]\n"
usage_message+="      Change the priority of an item\n"
usage_message+="      Example: $TODO_SH $(basename $0) 1 B 2.15"

source $(dirname $(readlink -nf "$BASH_SOURCE"))/common

[ "$#" -lt 2 -o "$#" -gt 3 ] && usage "Need 2 or 3 arguments"

line="$1"
priority="$2"
additional_prio=$(get_additional_prio_with_defaults "${3:-1.00}")

assert_matches_pattern_show_usage "$line" "^[0-9]+$" "ITEM# should be a number. It is: $line"
assert_matches_pattern_show_usage "$priority" "^[A-Z]$" "PRIORITY should be a value between A to Z. It is: $priority"
assert_matches_pattern_show_usage "$additional_prio" "^[0-9]\.[0-9][0-9]$" "ADDITIONAL_PRIORITY should be a value between 0.00 to 9.99. It is: $additional_prio"

sed -i -e "${line}"'s/^([A-Z]) \[[0-9]\.[0-9][0-9]\]/('"${priority}"') ['"${additional_prio}"']/' "${TODO_FILE}"

sed -n "${line}p" "${TODO_FILE}"
